// Code generated by protoc-gen-go.
// source: rank.proto
// DO NOT EDIT!

/*
Package rank is a generated protocol buffer package.

It is generated from these files:
	rank.proto

It has these top-level messages:
	CCSUsrMsg_ServerRankUpdate
*/
package rank

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CCSUsrMsg_ServerRankUpdate struct {
	RankUpdate       []*CCSUsrMsg_ServerRankUpdate_RankUpdate `protobuf:"bytes,1,rep,name=rank_update,json=rankUpdate" json:"rank_update,omitempty"`
	XXX_unrecognized []byte                                   `json:"-"`
}

func (m *CCSUsrMsg_ServerRankUpdate) Reset()                    { *m = CCSUsrMsg_ServerRankUpdate{} }
func (m *CCSUsrMsg_ServerRankUpdate) String() string            { return proto.CompactTextString(m) }
func (*CCSUsrMsg_ServerRankUpdate) ProtoMessage()               {}
func (*CCSUsrMsg_ServerRankUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CCSUsrMsg_ServerRankUpdate) GetRankUpdate() []*CCSUsrMsg_ServerRankUpdate_RankUpdate {
	if m != nil {
		return m.RankUpdate
	}
	return nil
}

type CCSUsrMsg_ServerRankUpdate_RankUpdate struct {
	AccountId        *int32   `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	RankOld          *int32   `protobuf:"varint,2,opt,name=rank_old,json=rankOld" json:"rank_old,omitempty"`
	RankNew          *int32   `protobuf:"varint,3,opt,name=rank_new,json=rankNew" json:"rank_new,omitempty"`
	NumWins          *int32   `protobuf:"varint,4,opt,name=num_wins,json=numWins" json:"num_wins,omitempty"`
	RankChange       *float32 `protobuf:"fixed32,5,opt,name=rank_change,json=rankChange" json:"rank_change,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CCSUsrMsg_ServerRankUpdate_RankUpdate) Reset()         { *m = CCSUsrMsg_ServerRankUpdate_RankUpdate{} }
func (m *CCSUsrMsg_ServerRankUpdate_RankUpdate) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_ServerRankUpdate_RankUpdate) ProtoMessage()    {}
func (*CCSUsrMsg_ServerRankUpdate_RankUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

func (m *CCSUsrMsg_ServerRankUpdate_RankUpdate) GetAccountId() int32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CCSUsrMsg_ServerRankUpdate_RankUpdate) GetRankOld() int32 {
	if m != nil && m.RankOld != nil {
		return *m.RankOld
	}
	return 0
}

func (m *CCSUsrMsg_ServerRankUpdate_RankUpdate) GetRankNew() int32 {
	if m != nil && m.RankNew != nil {
		return *m.RankNew
	}
	return 0
}

func (m *CCSUsrMsg_ServerRankUpdate_RankUpdate) GetNumWins() int32 {
	if m != nil && m.NumWins != nil {
		return *m.NumWins
	}
	return 0
}

func (m *CCSUsrMsg_ServerRankUpdate_RankUpdate) GetRankChange() float32 {
	if m != nil && m.RankChange != nil {
		return *m.RankChange
	}
	return 0
}

func init() {
	proto.RegisterType((*CCSUsrMsg_ServerRankUpdate)(nil), "CCSUsrMsg_ServerRankUpdate")
	proto.RegisterType((*CCSUsrMsg_ServerRankUpdate_RankUpdate)(nil), "CCSUsrMsg_ServerRankUpdate.RankUpdate")
}

func init() { proto.RegisterFile("rank.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x4a, 0xcc, 0xcb,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x6a, 0x65, 0xe2, 0x92, 0x72, 0x76, 0x0e, 0x0e, 0x2d,
	0x2e, 0xf2, 0x2d, 0x4e, 0x8f, 0x0f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x0a, 0x4a, 0xcc, 0xcb, 0x0e,
	0x2d, 0x48, 0x49, 0x2c, 0x49, 0x15, 0x72, 0xe7, 0xe2, 0x06, 0x29, 0x8e, 0x2f, 0x05, 0x73, 0x25,
	0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0xd4, 0xf4, 0x70, 0xeb, 0xd0, 0x43, 0x30, 0x83, 0xc0, 0xf6,
	0x40, 0xd8, 0x52, 0x73, 0x19, 0xb9, 0xb8, 0x90, 0xcc, 0x95, 0xe5, 0xe2, 0x4a, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0x89, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0xe2, 0x84, 0x8a,
	0x78, 0xa6, 0x08, 0x49, 0x72, 0x71, 0x80, 0xad, 0xcd, 0xcf, 0x49, 0x91, 0x60, 0x02, 0x4b, 0xb2,
	0x83, 0xf8, 0xfe, 0x39, 0x08, 0xa9, 0xbc, 0xd4, 0x72, 0x09, 0x66, 0x84, 0x94, 0x5f, 0x6a, 0x39,
	0x48, 0x2a, 0xaf, 0x34, 0x37, 0xbe, 0x3c, 0x33, 0xaf, 0x58, 0x82, 0x05, 0x22, 0x95, 0x57, 0x9a,
	0x1b, 0x9e, 0x99, 0x57, 0x2c, 0x24, 0x0f, 0xf5, 0x47, 0x72, 0x46, 0x62, 0x5e, 0x7a, 0xaa, 0x04,
	0xab, 0x02, 0xa3, 0x06, 0x13, 0xc4, 0x7d, 0xce, 0x60, 0x11, 0x27, 0x56, 0x0f, 0xc6, 0x06, 0x46,
	0x06, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x09, 0x32, 0x77, 0x1b, 0x01, 0x00, 0x00,
}
